INSERT INTO public.commercial_gaskets (brand, equipment_model)
SELECT v.brand, v.equipment_model
FROM (VALUES
  ('True', 'T-23-HC'),
  ('True', 'T-49-HC'),
  ('True', 'T-72-HC'),
  ('True', 'T-23F-HC'),
  ('True', 'T-49F-HC'),
  ('True', 'GDM-23-HC'),
  ('True', 'GDM-49-HC'),
  ('True', 'GDM-72-HC'),
  ('True', 'TSSU-27-08'),
  ('True', 'TSSU-48-12'),
  ('True', 'TUC-27-HC'),
  ('True', 'TWT-72-HC'),
  ('Turbo Air', 'M3R24-1'),
  ('Turbo Air', 'M3R47-2'),
  ('Turbo Air', 'M3R72-3'),
  ('Turbo Air', 'M3F24-1'),
  ('Turbo Air', 'M3F47-2'),
  ('Turbo Air', 'TSR-23SD'),
  ('Turbo Air', 'TSR-49SD'),
  ('Turbo Air', 'MST-28'),
  ('Turbo Air', 'MST-48'),
  ('Turbo Air', 'MST-72'),
  ('Turbo Air', 'TUF-28SD'),
  ('Beverage-Air', 'HR1HC-1S'),
  ('Beverage-Air', 'HR2HC-1S'),
  ('Beverage-Air', 'HR3HC-1S'),
  ('Beverage-Air', 'HF1HC-1S'),
  ('Beverage-Air', 'HF2HC-1S'),
  ('Beverage-Air', 'BB48HC'),
  ('Beverage-Air', 'BB72HC'),
  ('Beverage-Air', 'MT27'),
  ('Beverage-Air', 'MT45'),
  ('Beverage-Air', 'SPE48HC'),
  ('Hoshizaki', 'HR1A-FS'),
  ('Hoshizaki', 'HR2A-FS'),
  ('Hoshizaki', 'HR3A-FS'),
  ('Hoshizaki', 'F1A-FS'),
  ('Hoshizaki', 'F2A-FS'),
  ('Hoshizaki', 'PT1A-FS'),
  ('Hoshizaki', 'PT2A-FS'),
  ('Hoshizaki', 'HUC27A'),
  ('Traulsen', 'G10010'),
  ('Traulsen', 'G20010'),
  ('Traulsen', 'G30010'),
  ('Traulsen', 'G12010'),
  ('Traulsen', 'G22010'),
  ('Traulsen', 'UPT4812'),
  ('Traulsen', 'UHT27'),
  ('Delfield', '4448N'),
  ('Delfield', '4472N'),
  ('Delfield', 'GAR1P-S'),
  ('Delfield', 'GAR2P-S'),
  ('Delfield', 'UC4048'),
  ('Delfield', 'UC4148'),
  ('Arctic Air', 'AR23'),
  ('Arctic Air', 'AR49'),
  ('Arctic Air', 'AR72'),
  ('Arctic Air', 'AF23'),
  ('Arctic Air', 'AF49'),
  ('Arctic Air', 'AST48'),
  ('Arctic Air', 'AST72'),
  ('Arctic Air', 'ABB48'),
  ('Atosa', 'MBF8001'),
  ('Atosa', 'MBF8002'),
  ('Atosa', 'MBF8003'),
  ('Atosa', 'MCF8701'),
  ('Atosa', 'MPF8201'),
  ('Atosa', 'MPF8202'),
  ('Atosa', 'MBB59G'),
  ('Everest', 'ESR1'),
  ('Everest', 'ESR2'),
  ('Everest', 'ESR3'),
  ('Everest', 'ESF1'),
  ('Everest', 'ESF2'),
  ('Everest', 'EPTWR2'),
  ('Everest', 'EBB59'),
  ('Continental', 'D1R'),
  ('Continental', 'D2R'),
  ('Continental', 'D3R'),
  ('Continental', 'D1F'),
  ('Continental', 'D2F'),
  ('Continental', 'SW27'),
  ('Migali', 'C-1R'),
  ('Migali', 'C-2R'),
  ('Migali', 'C-3R'),
  ('Migali', 'C-1F'),
  ('Migali', 'C-2F'),
  ('Migali', 'C-PP48'),
  ('Master-Bilt', 'MBGR6'),
  ('Master-Bilt', 'MBGR48'),
  ('Master-Bilt', 'MBF8503'),
  ('Master-Bilt', 'BMG23'),
  ('Avantco', 'A-23R-HC'),
  ('Avantco', 'A-49R-HC'),
  ('Avantco', 'APT-48-HC'),
  ('Nor-Lake', 'KODF7766-C'),
  ('Nor-Lake', 'KL7810-C'),
  ('Hussmann', 'RLN'),
  ('Hussmann', 'D5X'),
  ('Hussmann', 'Excel'),
  ('Hussmann', 'Innovator'),
  ('Hillphoenix', 'O5DM'),
  ('Hillphoenix', 'O6DM'),
  ('Hillphoenix', 'RGD'),
  ('Anthony', '101 Series'),
  ('Anthony', '401 Series'),
  ('Zero Zone', 'Reveal'),
  ('Zero Zone', 'Genesis'),
  ('Kolpak', 'Kold Locker Series'),
  ('AmeriKooler', 'QC060872 Series')
) AS v(brand, equipment_model)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.commercial_gaskets cg
  WHERE lower(cg.brand) = lower(v.brand)
    AND upper(cg.equipment_model) = upper(v.equipment_model)
);
